remote_theme: pages-themes/cayman@v0.2.0
title: UT Dallas Japanese Language Association
description: We are a club for students of the Japanese language, both in classes and in self study.
plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
header_pages:
  - index.md
  - resources/index.md
